'use strict';

/**
 * MySQL Binlog Event Types.
 * These are specific event codes found in the binlog header.
 */
const EVENT_TYPE = {
  UNKNOWN_EVENT: 0x00,
  START_EVENT_V3: 0x01, // Deprecated, replaced by FORMAT_DESCRIPTION_EVENT
  QUERY_EVENT: 0x02,
  STOP_EVENT: 0x03,
  ROTATE_EVENT: 0x04,
  INTVAR_EVENT: 0x05,
  LOAD_EVENT: 0x06, // Deprecated in MySQL 5.0+, replaced by BEGIN/EXECUTE_LOAD_QUERY_EVENT
  SLAVE_EVENT: 0x07, // Deprecated, internal event
  CREATE_FILE_EVENT: 0x08, // Deprecated
  APPEND_BLOCK_EVENT: 0x09, // Deprecated
  EXEC_LOAD_EVENT: 0x0A, // Deprecated
  DELETE_FILE_EVENT: 0x0B, // Deprecated
  NEW_LOAD_EVENT: 0x0C, // Deprecated
  RAND_EVENT: 0x0D,
  USER_VAR_EVENT: 0x0E,
  FORMAT_DESCRIPTION_EVENT: 0x0F, // Introduced in MySQL 4.0.x
  XID_EVENT: 0x10, // Transaction ID event for XA transactions
  BEGIN_LOAD_QUERY_EVENT: 0x11,
  EXECUTE_LOAD_QUERY_EVENT: 0x12,
  TABLE_MAP_EVENT: 0x13, // Defines table structure for row-based replication
  PRE_GA_WRITE_ROWS_EVENT: 0x14, // Deprecated, old format Write Rows
  PRE_GA_UPDATE_ROWS_EVENT: 0x15, // Deprecated, old format Update Rows
  PRE_GA_DELETE_ROWS_EVENT: 0x16, // Deprecated, old format Delete Rows
  WRITE_ROWS_EVENT_V1: 0x17, // Write Rows Event V1
  UPDATE_ROWS_EVENT_V1: 0x18, // Update Rows Event V1
  DELETE_ROWS_EVENT_V1: 0x19, // Delete Rows Event V1
  INCIDENT_EVENT: 0x1A, // Used to notify if something happened on the master
  HEARTBEAT_LOG_EVENT: 0x1B,
  IGNORABLE_LOG_EVENT: 0x1C, // Events that can be ignored by slave
  ROWS_QUERY_LOG_EVENT: 0x1D, // Query that produced the row events (for info only)
  WRITE_ROWS_EVENT_V2: 0x1E, // Write Rows Event V2 (with extra data)
  UPDATE_ROWS_EVENT_V2: 0x1F, // Update Rows Event V2 (with extra data)
  DELETE_ROWS_EVENT_V2: 0x20, // Delete Rows Event V2 (with extra data)
  GTID_EVENT: 0x21, // MySQL 5.6+ GTID event
  ANONYMOUS_GTID_LOG_EVENT: 0x22, // Used for anonymous transactions in GTID mode
  PREVIOUS_GTIDS_LOG_EVENT: 0x23, // Contains GTIDs from the previous binlog file
  XA_PREPARE_LOG_EVENT: 0x26, // XA prepare event (MySQL 8.0+)
  PARTIAL_UPDATE_ROWS_EVENT: 0x27, // For partial JSON updates (MySQL 8.0+)
};

/**
 * Types for INTVAR events.
 */
const INTVAR_TYPE = {
  INTVAR_INVALID_INT_EVENT: 0x00,
  INTVAR_LAST_INSERT_ID_EVENT: 0x01,
  INTVAR_INSERT_ID_EVENT: 0x02,
};

/**
 * MariaDB Specific Event Types.
 */
const MARIADB_EVENT = {
  MARIADB_ANNOTATE_ROWS_EVENT: 0xA0, // MariaDB specific annotation event for row-based replication
  MARIADB_BINLOG_CHECKPOINT_EVENT: 0xA1, // MariaDB specific binlog checkpoint event
  MARIADB_GTID_EVENT: 0xA2, // MariaDB specific GTID event (different from MySQL's)
  MARIADB_GTID_LIST_EVENT: 0xA3, // MariaDB GTID List event
  MARIADB_START_ENCRYPTION_EVENT: 0xA4, // MariaDB encryption event
};

// Export all constants
module.exports = {
  // Event Types
  UNKNOWN_EVENT: EVENT_TYPE.UNKNOWN_EVENT,
  START_EVENT_V3: EVENT_TYPE.START_EVENT_V3,
  QUERY_EVENT: EVENT_TYPE.QUERY_EVENT,
  STOP_EVENT: EVENT_TYPE.STOP_EVENT,
  ROTATE_EVENT: EVENT_TYPE.ROTATE_EVENT,
  INTVAR_EVENT: EVENT_TYPE.INTVAR_EVENT,
  LOAD_EVENT: EVENT_TYPE.LOAD_EVENT,
  SLAVE_EVENT: EVENT_TYPE.SLAVE_EVENT,
  CREATE_FILE_EVENT: EVENT_TYPE.CREATE_FILE_EVENT,
  APPEND_BLOCK_EVENT: EVENT_TYPE.APPEND_BLOCK_EVENT,
  EXEC_LOAD_EVENT: EVENT_TYPE.EXEC_LOAD_EVENT,
  DELETE_FILE_EVENT: EVENT_TYPE.DELETE_FILE_EVENT,
  NEW_LOAD_EVENT: EVENT_TYPE.NEW_LOAD_EVENT,
  RAND_EVENT: EVENT_TYPE.RAND_EVENT,
  USER_VAR_EVENT: EVENT_TYPE.USER_VAR_EVENT,
  FORMAT_DESCRIPTION_EVENT: EVENT_TYPE.FORMAT_DESCRIPTION_EVENT,
  XID_EVENT: EVENT_TYPE.XID_EVENT,
  BEGIN_LOAD_QUERY_EVENT: EVENT_TYPE.BEGIN_LOAD_QUERY_EVENT,
  EXECUTE_LOAD_QUERY_EVENT: EVENT_TYPE.EXECUTE_LOAD_QUERY_EVENT,
  TABLE_MAP_EVENT: EVENT_TYPE.TABLE_MAP_EVENT,
  PRE_GA_WRITE_ROWS_EVENT: EVENT_TYPE.PRE_GA_WRITE_ROWS_EVENT,
  PRE_GA_UPDATE_ROWS_EVENT: EVENT_TYPE.PRE_GA_UPDATE_ROWS_EVENT,
  PRE_GA_DELETE_ROWS_EVENT: EVENT_TYPE.PRE_GA_DELETE_ROWS_EVENT,
  WRITE_ROWS_EVENT_V1: EVENT_TYPE.WRITE_ROWS_EVENT_V1,
  UPDATE_ROWS_EVENT_V1: EVENT_TYPE.UPDATE_ROWS_EVENT_V1,
  DELETE_ROWS_EVENT_V1: EVENT_TYPE.DELETE_ROWS_EVENT_V1,
  INCIDENT_EVENT: EVENT_TYPE.INCIDENT_EVENT,
  HEARTBEAT_LOG_EVENT: EVENT_TYPE.HEARTBEAT_LOG_EVENT,
  IGNORABLE_LOG_EVENT: EVENT_TYPE.IGNORABLE_LOG_EVENT,
  ROWS_QUERY_LOG_EVENT: EVENT_TYPE.ROWS_QUERY_LOG_EVENT,
  WRITE_ROWS_EVENT_V2: EVENT_TYPE.WRITE_ROWS_EVENT_V2,
  UPDATE_ROWS_EVENT_V2: EVENT_TYPE.UPDATE_ROWS_EVENT_V2,
  DELETE_ROWS_EVENT_V2: EVENT_TYPE.DELETE_ROWS_EVENT_V2,
  GTID_EVENT: EVENT_TYPE.GTID_EVENT,
  ANONYMOUS_GTID_LOG_EVENT: EVENT_TYPE.ANONYMOUS_GTID_LOG_EVENT,
  PREVIOUS_GTIDS_LOG_EVENT: EVENT_TYPE.PREVIOUS_GTIDS_LOG_EVENT,
  XA_PREPARE_LOG_EVENT: EVENT_TYPE.XA_PREPARE_LOG_EVENT,
  PARTIAL_UPDATE_ROWS_EVENT: EVENT_TYPE.PARTIAL_UPDATE_ROWS_EVENT,

  // INTVAR Types
  INTVAR_INVALID_INT_EVENT: INTVAR_TYPE.INTVAR_INVALID_INT_EVENT,
  INTVAR_LAST_INSERT_ID_EVENT: INTVAR_TYPE.INTVAR_LAST_INSERT_ID_EVENT,
  INTVAR_INSERT_ID_EVENT: INTVAR_TYPE.INTVAR_INSERT_ID_EVENT,

  // MariaDB Events
  MARIADB_ANNOTATE_ROWS_EVENT: MARIADB_EVENT.MARIADB_ANNOTATE_ROWS_EVENT,
  MARIADB_BINLOG_CHECKPOINT_EVENT: MARIADB_EVENT.MARIADB_BINLOG_CHECKPOINT_EVENT,
  MARIADB_GTID_EVENT: MARIADB_EVENT.MARIADB_GTID_EVENT,
  MARIADB_GTID_LIST_EVENT: MARIADB_EVENT.MARIADB_GTID_GTID_LIST_EVENT, // Renamed for consistency with Python
  MARIADB_START_ENCRYPTION_EVENT: MARIADB_EVENT.MARIADB_START_ENCRYPTION_EVENT,

  // Common Binlog Constants
  BINLOG_CHECKSUM_LEN: 4, // Length of the CRC32 checksum at the end of each event (if enabled)
};
