'use strict'
// Query Event Status Variable Codes
module.exports = {
  Q_FLAGS2_CODE: 0x00,
  Q_SQL_MODE_CODE: 0x01,
  Q_CATALOG_CODE: 0x02,
  Q_AUTO_INCREMENT: 0x03,
  Q_CHARSET_CODE: 0x04,
  Q_TIME_ZONE_CODE: 0x05,
  Q_CATALOG_NZ_CODE: 0x06,
  Q_LC_TIME_NAMES_CODE: 0x07,
  Q_CHARSET_DATABASE_CODE: 0x08,
  Q_TABLE_MAP_FOR_UPDATE_CODE: 0x09,
  Q_MASTER_DATA_WRITTEN_CODE: 0x0A,
  Q_INVOKER: 0x0B,
  Q_UPDATED_DB_NAMES: 0x0C,
  Q_MICROSECONDS: 0x0D,
  Q_COMMIT_TS: 0x0E,
  Q_COMMIT_TS2: 0x0F,
  Q_EXPLICIT_DEFAULTS_FOR_TIMESTAMP: 0x10,
  Q_DDL_LOGGED_WITH_XID: 0x11,
  Q_DEFAULT_COLLATION_FOR_UTF8MB4: 0x12,
  Q_SQL_REQUIRE_PRIMARY_KEY: 0x13,
  Q_DEFAULT_TABLE_ENCRYPTION: 0x14,
  Q_HRNOW: 0x15, // High Resolution Now (MySQL 8.0.1)
  Q_XID: 0x16, // Transaction XID (MySQL 8.0.1)
};
